<a href="https://colab.research.google.com/github/Purohit1999/Data_Science/blob/main/Label_propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits
from sklearn.semi_supervised import LabelPropagation,LabelSpreading
from sklearn.metrics import accuracy_score

In [ ]:
data=load_digits()
df=pd.DataFrame(data.data,columns=data.feature_names)
df['target']=data.target
df.head()

,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_1_0,pixel_1_1,...,pixel_6_7,pixel_7_0,pixel_7_1,pixel_7_2,pixel_7_3,pixel_7_4,pixel_7_5,pixel_7_6,pixel_7_7,target
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4

In [ ]:
df.info()

In [ ]:
df['target'].unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
X=df.iloc[:,:-1]   #X=df.drop('target',axis=1)
y=df['target']      #y=df.iloc[:,-1]

In [ ]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)

In [ ]:
ytrain[100:]=-1
ytrain

513     8.0
81      7.0
596     1.0
380     4.0
1521    6.0
       ...
1130   -1.0
1294   -1.0
860    -1.0
1459   -1.0
1126   -1.0
Name: target, Length: 1257, dtype: float64

In [ ]:
model=LabelPropagation(kernel='rbf',gamma=0.9)
model.fit(Xtrain,ytrain)
ypred=model.predict(Xtest)
accuracy_score(ytest,ypred)

/usr/local/lib/python3.11/dist-packages/sklearn/semi_supervised/_label_propagation.py:231: RuntimeWarning: invalid value encountered in divide
  probabilities /= normalizer

0.9611111111111111